kind: Deployment
apiVersion: apps/v1
metadata:
  name: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana
      env: prod
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
        env: prod
    spec:
      containers:
        - name: loki
          image: grafana/loki:1.5.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3100
          resources:
            limits:
              memory: "1Gi"
              cpu: "800m"
            requests:
              memory: "1Gi"
              cpu: "600m"
        - name: promtail
          image: grafana/promtail:1.5.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "800m"
            requests:
              memory: "1Gi"
              cpu: "600m"
          volumeMounts:
            - name: grafana-pv
              mountPath: /var/log
        - name: grafana
          image: grafana/grafana:master
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1Gi"
              cpu: "800m"
            requests:
              memory: "1Gi"
              cpu: "600m"
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc