kind: Service
apiVersion: v1
metadata:
  name: grafana-server
spec:
  type: LoadBalancer
  selector:
    app: grafana
    env: prod
  ports:
    - name: loki
      port: 3100
      targetPort: 3100
    - name: grafana
      port: 80
      targetPort: 3000