apiVersion: v1
kind: Service
metadata:
  name: mongo-nlweb
  labels:
    name: mongo-nlweb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: access-port
    port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 31845
  selector:
    role: mongo-nlweb
  type: LoadBalancer