kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-nlweb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ci-storage-def